#!/usr/bin/env bash

# script to create route53 dns entries for all peers of a dsnet (https://github.com/naggie/dsnet) manged wireguard network

# requires https://github.com/barnybug/cli53 and https://github.com/stedolan/jq

set -e

usage() { echo "Usage: $0 [-i <file.json>] [-d <domain>] [-s <subdomain>.] -r" 1>&2; exit 1; }

while getopts ":i:d:s:r6" o; do
    case "${o}" in
        i)
            input=${OPTARG}
            ;;
        s)
            subdomain=${OPTARG}
            ;;

        d)
            domain=${OPTARG}
            ;;
        r)
            dryRun=1 
            ;;
        6)
            v6=1 
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${input}" ] || [ -z "${domain}" ]; then
    usage
fi

ekko=""
if [ "${dryRun}" == 1 ]; then
  ekko="echo "
fi


for entry in $(jq -r  '.Peers[] | { Hostname, IP} | flatten | @csv '  "${input}")
do
    sub="${subdomain:-}"
    record=(${entry//,/ })
    ${ekko} cli53 rrcreate --replace ${domain} "${record[0]//\"}.$sub 86400 A ${record[1]//\"}"
done


if [ "$v6" == 1 ] ; then 
    for entry in $(jq -r  '.Peers[] | { Hostname, IP6} | flatten | @csv '  "${input}")
    do
        sub="${subdomain:-}"
        record=(${entry//,/ })
        ${ekko} cli53 rrcreate --replace ${domain} "${record[0]//\"}.$sub 86400 AAAA ${record[1]//\"}"
    done
fi
