#!/usr/bin/env bash

if [ "$1" == "" ] || [ "$1" == "-h" ]
then
    echo "usage: show-cert <hostname>"
    exit 1
fi

echo | openssl s_client -showcerts -servername "$1" -connect "$1":443 2>/dev/null | openssl x509 -inform pem -noout -text

